ruby '2.5.1'
source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'sequel'
gem 'json'
gem 'haml'
gem 'mustache'
gem 'data_uri'
gem 'redcarpet'
gem 'puma'
gem 'thin'
gem 'daemons'
gem 'netaddr'
gem 'nokogiri'
gem 'pg'
gem 'sqlite3'
gem 'rubyXL'
gem 'rubyzip', '>= 1.2.1'
gem 'bcrypt'
group :test do
    gem 'database_cleaner'
    gem 'cucumber-sinatra'
    gem 'cucumber'
    gem 'capybara'
    gem 'capybara-screenshot'
    gem 'rspec'
    gem 'selenium-cucumber'
    gem 'selenium-webdriver'
end
gem 'rack-contrib'
gem 'yard'
github 'sinatra/sinatra' do
  gem 'rack-protection'
  gem 'sinatra-contrib'
end
